/**
 * Curated global college directory — seeded into the DB on boot (idempotent).
 * Students can also add their own college at signup if it's missing here;
 * the college-email OTP verification step is the real gate, not this list.
 * Each college's emailDomain is the official student-mail domain
 * (e.g. IPEC → ipec.org.in) that OTP verification enforces.
 */
export interface CollegeSeed {
  name: string;
  shortName?: string;
  city?: string;
  state?: string;
  emailDomain?: string;
}

export const COLLEGE_SEED: CollegeSeed[] = [
  // ── India: IITs ──
  { name: 'Indian Institute of Technology Bombay', shortName: 'IIT Bombay', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'iitb.ac.in' },
  { name: 'Indian Institute of Technology Delhi', shortName: 'IIT Delhi', city: 'New Delhi', state: 'Delhi', emailDomain: 'iitd.ac.in' },
  { name: 'Indian Institute of Technology Madras', shortName: 'IIT Madras', city: 'Chennai', state: 'Tamil Nadu', emailDomain: 'iitm.ac.in' },
  { name: 'Indian Institute of Technology Kanpur', shortName: 'IIT Kanpur', city: 'Kanpur', state: 'Uttar Pradesh', emailDomain: 'iitk.ac.in' },
  { name: 'Indian Institute of Technology Kharagpur', shortName: 'IIT KGP', city: 'Kharagpur', state: 'West Bengal', emailDomain: 'iitkgp.ac.in' },
  { name: 'Indian Institute of Technology Roorkee', shortName: 'IIT Roorkee', city: 'Roorkee', state: 'Uttarakhand', emailDomain: 'iitr.ac.in' },
  { name: 'Indian Institute of Technology Guwahati', shortName: 'IIT Guwahati', city: 'Guwahati', state: 'Assam', emailDomain: 'iitg.ac.in' },
  { name: 'Indian Institute of Technology Hyderabad', shortName: 'IIT Hyderabad', city: 'Hyderabad', state: 'Telangana', emailDomain: 'iith.ac.in' },
  { name: 'Indian Institute of Technology Varanasi', shortName: 'IIT BHU', city: 'Varanasi', state: 'Uttar Pradesh', emailDomain: 'iitbhu.ac.in' },
  { name: 'Indian Institute of Technology Indore', shortName: 'IIT Indore', city: 'Indore', state: 'Madhya Pradesh', emailDomain: 'iiti.ac.in' },
  { name: 'Indian Institute of Technology Gandhinagar', shortName: 'IIT GN', city: 'Gandhinagar', state: 'Gujarat', emailDomain: 'iitgn.ac.in' },
  { name: 'Indian Institute of Technology Jodhpur', shortName: 'IIT Jodhpur', city: 'Jodhpur', state: 'Rajasthan', emailDomain: 'iitj.ac.in' },
  { name: 'Indian Institute of Technology Patna', shortName: 'IIT Patna', city: 'Patna', state: 'Bihar', emailDomain: 'iitp.ac.in' },
  { name: 'Indian Institute of Technology Bhubaneswar', shortName: 'IIT BBS', city: 'Bhubaneswar', state: 'Odisha', emailDomain: 'iitbbs.ac.in' },
  { name: 'Indian Institute of Technology Mandi', shortName: 'IIT Mandi', city: 'Mandi', state: 'Himachal Pradesh', emailDomain: 'iitmandi.ac.in' },
  { name: 'Indian Institute of Technology Palakkad', shortName: 'IIT Palakkad', city: 'Palakkad', state: 'Kerala', emailDomain: 'iitpkd.ac.in' },
  { name: 'Indian Institute of Technology Tirupati', shortName: 'IIT Tirupati', city: 'Tirupati', state: 'Andhra Pradesh', emailDomain: 'iittp.ac.in' },
  { name: 'Indian Institute of Technology Jammu', shortName: 'IIT Jammu', city: 'Jammu', state: 'J&K', emailDomain: 'iitjammu.ac.in' },
  { name: 'Indian Institute of Technology Dharwad', shortName: 'IIT Dharwad', city: 'Dharwad', state: 'Karnataka', emailDomain: 'iitdh.ac.in' },
  { name: 'Indian Institute of Technology Bhilai', shortName: 'IIT Bhilai', city: 'Bhilai', state: 'Chhattisgarh', emailDomain: 'iitbhilai.ac.in' },
  { name: 'Indian Institute of Technology Goa', shortName: 'IIT Goa', city: 'Goa', state: 'Goa', emailDomain: 'iitgoa.ac.in' },
  { name: 'Indian Institute of Technology Ropar', shortName: 'IIT Ropar', city: 'Rupnagar', state: 'Punjab', emailDomain: 'iiitpr.ac.in' },

  // ── India: NITs ──
  { name: 'National Institute of Technology Tiruchirappalli', shortName: 'NIT Trichy', city: 'Tiruchirappalli', state: 'Tamil Nadu', emailDomain: 'nitt.edu' },
  { name: 'National Institute of Technology Surathkal', shortName: 'NITK', city: 'Mangaluru', state: 'Karnataka', emailDomain: 'nitk.edu.in' },
  { name: 'National Institute of Technology Warangal', shortName: 'NIT Warangal', city: 'Warangal', state: 'Telangana', emailDomain: 'nitw.ac.in' },
  { name: 'National Institute of Technology Calicut', shortName: 'NIT Calicut', city: 'Kozhikode', state: 'Kerala', emailDomain: 'nitc.ac.in' },
  { name: 'Motilal Nehru National Institute of Technology Allahabad', shortName: 'MNNIT', city: 'Prayagraj', state: 'Uttar Pradesh', emailDomain: 'mnnit.ac.in' },
  { name: 'Malaviya National Institute of Technology Jaipur', shortName: 'MNIT', city: 'Jaipur', state: 'Rajasthan', emailDomain: 'mnit.ac.in' },
  { name: 'National Institute of Technology Rourkela', shortName: 'NIT Rourkela', city: 'Rourkela', state: 'Odisha', emailDomain: 'nitrkl.ac.in' },
  { name: 'Visvesvaraya National Institute of Technology Nagpur', shortName: 'VNIT', city: 'Nagpur', state: 'Maharashtra', emailDomain: 'vnit.ac.in' },
  { name: 'Sardar Vallabhbhai National Institute of Technology Surat', shortName: 'SVNIT', city: 'Surat', state: 'Gujarat', emailDomain: 'svnit.ac.in' },
  { name: 'National Institute of Technology Kurukshetra', shortName: 'NIT KKR', city: 'Kurukshetra', state: 'Haryana', emailDomain: 'nitkkr.ac.in' },
  { name: 'National Institute of Technology Durgapur', shortName: 'NIT DGP', city: 'Durgapur', state: 'West Bengal', emailDomain: 'nitdgp.ac.in' },
  { name: 'National Institute of Technology Silchar', shortName: 'NIT Silchar', city: 'Silchar', state: 'Assam', emailDomain: 'nits.ac.in' },
  { name: 'National Institute of Technology Hamirpur', shortName: 'NIT Hamirpur', city: 'Hamirpur', state: 'Himachal Pradesh', emailDomain: 'nith.ac.in' },
  { name: 'National Institute of Technology Jalandhar', shortName: 'NIT Jalandhar', city: 'Jalandhar', state: 'Punjab', emailDomain: 'nitj.ac.in' },
  { name: 'National Institute of Technology Patna', shortName: 'NIT Patna', city: 'Patna', state: 'Bihar', emailDomain: 'nitp.ac.in' },
  { name: 'National Institute of Technology Raipur', shortName: 'NIT Raipur', city: 'Raipur', state: 'Chhattisgarh', emailDomain: 'nitrr.ac.in' },
  { name: 'National Institute of Technology Meghalaya', shortName: 'NIT Meghalaya', city: 'Shillong', state: 'Meghalaya', emailDomain: 'nitm.ac.in' },
  { name: 'National Institute of Technology Agartala', shortName: 'NIT Agartala', city: 'Agartala', state: 'Tripura', emailDomain: 'nitagartala.ac.in' },
  { name: 'National Institute of Technology Nagaland', shortName: 'NIT Nagaland', city: 'Chumukedima', state: 'Nagaland', emailDomain: 'nitnagaland.ac.in' },
  { name: 'National Institute of Technology Srinagar', shortName: 'NIT Srinagar', city: 'Srinagar', state: 'J&K', emailDomain: 'nitsri.ac.in' },
  { name: 'National Institute of Technology Manipur', shortName: 'NIT Manipur', city: 'Imphal', state: 'Manipur', emailDomain: 'nitmanipur.ac.in' },
  { name: 'National Institute of Technology Mizoram', shortName: 'NIT Mizoram', city: 'Aizawl', state: 'Mizoram', emailDomain: 'nitmz.ac.in' },
  { name: 'National Institute of Technology Sikkim', shortName: 'NIT Sikkim', city: 'Gangtok', state: 'Sikkim', emailDomain: 'nitsikkim.ac.in' },
  { name: 'National Institute of Technology Arunachal Pradesh', shortName: 'NIT AP', city: 'Yupia', state: 'Arunachal Pradesh', emailDomain: 'nitap.ac.in' },
  { name: 'National Institute of Technology Delhi', shortName: 'NIT Delhi', city: 'New Delhi', state: 'Delhi', emailDomain: 'nitdelhi.ac.in' },
  { name: 'National Institute of Technology Goa', shortName: 'NIT Goa', city: 'Goa', state: 'Goa', emailDomain: 'nitgoa.ac.in' },
  { name: 'National Institute of Technology Puducherry', shortName: 'NIT PY', city: 'Karaikal', state: 'Puducherry', emailDomain: 'nitpy.ac.in' },
  { name: 'National Institute of Technology Uttarakhand', shortName: 'NIT UK', city: 'Srinagar Garhwal', state: 'Uttarakhand', emailDomain: 'nituk.ac.in' },
  { name: 'National Institute of Technology Andhra Pradesh', shortName: 'NIT AP', city: 'Tadepalligudem', state: 'Andhra Pradesh', emailDomain: 'nitandhra.ac.in' },

  // ── India: IIITs ──
  { name: 'Indian Institute of Information Technology Hyderabad', shortName: 'IIIT-H', city: 'Hyderabad', state: 'Telangana', emailDomain: 'iiit.ac.in' },
  { name: 'Indian Institute of Information Technology Allahabad', shortName: 'IIIT-A', city: 'Prayagraj', state: 'Uttar Pradesh', emailDomain: 'iiita.ac.in' },
  { name: 'Indian Institute of Information Technology Bangalore', shortName: 'IIIT-B', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'iiitb.ac.in' },
  { name: 'Indian Institute of Information Technology Delhi', shortName: 'IIIT-D', city: 'New Delhi', state: 'Delhi', emailDomain: 'iiitd.ac.in' },
  { name: 'Indian Institute of Information Technology Pune', shortName: 'IIIT Pune', city: 'Pune', state: 'Maharashtra', emailDomain: 'iiitp.ac.in' },
  { name: 'Indian Institute of Information Technology Lucknow', shortName: 'IIIT-L', city: 'Lucknow', state: 'Uttar Pradesh', emailDomain: 'iiitl.ac.in' },
  { name: 'Indian Institute of Information Technology Nagpur', shortName: 'IIIT Nagpur', city: 'Nagpur', state: 'Maharashtra', emailDomain: 'iiitn.ac.in' },
  { name: 'Indian Institute of Information Technology Bhopal', shortName: 'IIIT Bhopal', city: 'Bhopal', state: 'Madhya Pradesh', emailDomain: 'iiitbhopal.ac.in' },
  { name: 'Indian Institute of Information Technology Jabalpur', shortName: 'IIITDMJ', city: 'Jabalpur', state: 'Madhya Pradesh', emailDomain: 'iiitdmj.ac.in' },
  { name: 'Indian Institute of Information Technology Kancheepuram', shortName: 'IIITDMK', city: 'Chennai', state: 'Tamil Nadu', emailDomain: 'iiitdmk.ac.in' },
  { name: 'Indian Institute of Information Technology Guwahati', shortName: 'IIIT Guwahati', city: 'Guwahati', state: 'Assam', emailDomain: 'iiitg.ac.in' },
  { name: 'Indian Institute of Information Technology Kota', shortName: 'IIIT Kota', city: 'Kota', state: 'Rajasthan', emailDomain: 'iiitkota.ac.in' },
  { name: 'Indian Institute of Information Technology Sri City', shortName: 'IIIT Sri City', city: 'Chittoor', state: 'Andhra Pradesh', emailDomain: 'iiitsri.ac.in' },
  { name: 'Indian Institute of Information Technology Vadodara', shortName: 'IIIT-V', city: 'Vadodara', state: 'Gujarat', emailDomain: 'iiitv.ac.in' },
  { name: 'Indian Institute of Information Technology Bhubaneswar', shortName: 'IIIT BBS', city: 'Bhubaneswar', state: 'Odisha', emailDomain: 'iiitbbsr.ac.in' },
  { name: 'Indian Institute of Information Technology Surat', shortName: 'IIIT Surat', city: 'Surat', state: 'Gujarat', emailDomain: 'iiitsurat.ac.in' },
  { name: 'Indian Institute of Information Technology Trichy', shortName: 'IIIT Trichy', city: 'Tiruchirappalli', state: 'Tamil Nadu', emailDomain: 'iiitt.ac.in' },
  { name: 'Indian Institute of Information Technology Ranchi', shortName: 'IIIT Ranchi', city: 'Ranchi', state: 'Jharkhand', emailDomain: 'iiitranchi.ac.in' },
  { name: 'Indian Institute of Information Technology Bhagalpur', shortName: 'IIIT Bhagalpur', city: 'Bhagalpur', state: 'Bihar', emailDomain: 'iiitbhagalpur.ac.in' },
  { name: 'Indian Institute of Information Technology Agartala', shortName: 'IIIT Agartala', city: 'Agartala', state: 'Tripura', emailDomain: 'iiitagartala.ac.in' },
  { name: 'Indian Institute of Information Technology Raichur', shortName: 'IIIT Raichur', city: 'Raichur', state: 'Karnataka', emailDomain: 'iiitraichur.ac.in' },
  { name: 'Indian Institute of Information Technology Dharwad', shortName: 'IIIT Dharwad', city: 'Dharwad', state: 'Karnataka', emailDomain: 'iiitdwd.ac.in' },
  { name: 'Indian Institute of Information Technology Kalyani', shortName: 'IIIT Kalyani', city: 'Kalyani', state: 'West Bengal', emailDomain: 'iiitkalyani.ac.in' },
  { name: 'Indian Institute of Information Technology Manipur', shortName: 'IIIT Manipur', city: 'Imphal', state: 'Manipur', emailDomain: 'iiitmanipur.ac.in' },
  { name: 'Indian Institute of Information Technology Sonepat', shortName: 'IIIT Sonepat', city: 'Sonipat', state: 'Haryana', emailDomain: 'iiitsonepat.ac.in' },
  { name: 'Indian Institute of Information Technology Una', shortName: 'IIIT Una', city: 'Una', state: 'Himachal Pradesh', emailDomain: 'iiituna.ac.in' },
  { name: 'Indian Institute of Information Technology Bhopal', shortName: 'IIITM', city: 'Gwalior', state: 'Madhya Pradesh', emailDomain: 'iiitm.ac.in' },

  // ── India: top government & central universities ──
  { name: 'Indian Institute of Science', shortName: 'IISc', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'iisc.ac.in' },
  { name: 'Delhi Technological University', shortName: 'DTU', city: 'New Delhi', state: 'Delhi', emailDomain: 'dtu.ac.in' },
  { name: 'Netaji Subhas University of Technology', shortName: 'NSUT', city: 'New Delhi', state: 'Delhi', emailDomain: 'nsut.ac.in' },
  { name: 'Indira Gandhi Delhi Technical University for Women', shortName: 'IGDTUW', city: 'New Delhi', state: 'Delhi', emailDomain: 'igdtuw.ac.in' },
  { name: 'Delhi Technological University East Campus', shortName: 'DTU East', city: 'New Delhi', state: 'Delhi', emailDomain: 'dtu.ac.in' },
  { name: 'Jamia Millia Islamia', shortName: 'JMI', city: 'New Delhi', state: 'Delhi', emailDomain: 'jmi.ac.in' },
  { name: 'Jawaharlal Nehru University', shortName: 'JNU', city: 'New Delhi', state: 'Delhi', emailDomain: 'jnu.ac.in' },
  { name: 'University of Delhi', shortName: 'DU', city: 'New Delhi', state: 'Delhi', emailDomain: 'du.ac.in' },
  { name: 'Indraprastha Institute of Information Technology Delhi', shortName: 'IIIT-Delhi', city: 'New Delhi', state: 'Delhi', emailDomain: 'iiitd.ac.in' },
  { name: 'Anna University', shortName: 'Anna Univ', city: 'Chennai', state: 'Tamil Nadu', emailDomain: 'annauniv.edu' },
  { name: 'College of Engineering Guindy', shortName: 'CEG', city: 'Chennai', state: 'Tamil Nadu', emailDomain: 'ceg.annauniv.edu' },
  { name: 'Cochin University of Science and Technology', shortName: 'CUSAT', city: 'Kochi', state: 'Kerala', emailDomain: 'cusat.ac.in' },
  { name: 'Jadavpur University', shortName: 'JU', city: 'Kolkata', state: 'West Bengal', emailDomain: 'jadavpur.edu.in' },
  { name: 'Institute of Engineering and Technology Lucknow', shortName: 'IET Lucknow', city: 'Lucknow', state: 'Uttar Pradesh', emailDomain: 'ietlucknow.ac.in' },
  { name: 'Punjab Engineering College', shortName: 'PEC', city: 'Chandigarh', state: 'Punjab', emailDomain: 'pec.ac.in' },
  { name: 'Dr B R Ambedkar National Institute of Technology Jalandhar', shortName: 'NITJ', city: 'Jalandhar', state: 'Punjab', emailDomain: 'nitj.ac.in' },
  { name: 'Guru Gobind Singh Indraprastha University', shortName: 'IPU', city: 'New Delhi', state: 'Delhi', emailDomain: 'ipu.ac.in' },
  { name: 'University of Mumbai', shortName: 'MU', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'mu.ac.in' },
  { name: 'Savitribai Phule Pune University', shortName: 'SPPU', city: 'Pune', state: 'Maharashtra', emailDomain: 'unipune.ac.in' },
  { name: 'Gujarat Technological University', shortName: 'GTU', city: 'Ahmedabad', state: 'Gujarat', emailDomain: 'gtu.ac.in' },
  { name: 'Osmania University', shortName: 'OU', city: 'Hyderabad', state: 'Telangana', emailDomain: 'osmania.ac.in' },
  { name: 'Bangalore University', shortName: 'BU', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'bangaloreuniversity.ac.in' },
  { name: 'University of Rajasthan', shortName: 'UNIRAJ', city: 'Jaipur', state: 'Rajasthan', emailDomain: 'uniraj.ernet.in' },
  { name: 'Bhopal University', shortName: 'BU Bhopal', city: 'Bhopal', state: 'Madhya Pradesh', emailDomain: 'bhu.ac.in' },

  // ── India: famous constituent & autonomous colleges ──
  // NOTE: plain ASCII apostrophes only — students type ' not ’, and the
  // typeahead matches raw substrings.
  { name: 'St. Stephen\'s College', shortName: 'St. Stephen\'s', city: 'New Delhi', state: 'Delhi', emailDomain: 'ststephens.edu' },
  { name: 'Hindu College', shortName: 'Hindu', city: 'New Delhi', state: 'Delhi', emailDomain: 'hinducollege.edu.in' },
  { name: 'Miranda House', shortName: 'Miranda House', city: 'New Delhi', state: 'Delhi', emailDomain: 'mirandahouse.ac.in' },
  { name: 'Hans Raj College', shortName: 'Hansraj', city: 'New Delhi', state: 'Delhi', emailDomain: 'hansrajcollege.edu.in' },
  { name: 'Kirori Mal College', shortName: 'KMC', city: 'New Delhi', state: 'Delhi', emailDomain: 'kmc.du.ac.in' },
  { name: 'Lady Shri Ram College', shortName: 'LSR', city: 'New Delhi', state: 'Delhi', emailDomain: 'lsr.edu.in' },
  { name: 'Ramjas College', shortName: 'Ramjas', city: 'New Delhi', state: 'Delhi', emailDomain: 'ramjas.du.ac.in' },
  { name: 'Sri Venkateswara College', shortName: 'Venky', city: 'New Delhi', state: 'Delhi', emailDomain: 'svc.du.ac.in' },
  { name: 'Jesus and Mary College', shortName: 'JMC', city: 'New Delhi', state: 'Delhi', emailDomain: 'jmc.du.ac.in' },
  { name: 'Gargi College', shortName: 'Gargi', city: 'New Delhi', state: 'Delhi', emailDomain: 'gargi.du.ac.in' },
  { name: 'Christ University', shortName: 'Christ', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'christuniversity.in' },
  { name: 'Mount Carmel College', shortName: 'MCC Bengaluru', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'mccblr.edu.in' },
  { name: 'St. Joseph\'s College Bengaluru', shortName: 'St. Joseph\'s', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'sjc.ac.in' },
  { name: 'St. Xavier\'s College Kolkata', shortName: 'Xaviers Kolkata', city: 'Kolkata', state: 'West Bengal', emailDomain: 'sxccal.edu' },
  { name: 'St. Xavier\'s College Mumbai', shortName: 'Xaviers Mumbai', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'xaviers.edu.in' },
  { name: 'H.R. College of Commerce and Economics', shortName: 'HR College', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'hrcollege.edu' },
  { name: 'Fergusson College', shortName: 'Fergusson', city: 'Pune', state: 'Maharashtra', emailDomain: 'fergusson.edu' },
  { name: 'Presidency University', shortName: 'Presidency', city: 'Kolkata', state: 'West Bengal', emailDomain: 'presiuniv.ac.in' },
  { name: 'Symbiosis International University', shortName: 'Symbiosis', city: 'Pune', state: 'Maharashtra', emailDomain: 'siu.edu.in' },

  // ── India: BITS, IISERs & research ──
  { name: 'Birla Institute of Technology and Science Pilani', shortName: 'BITS Pilani', city: 'Pilani', state: 'Rajasthan', emailDomain: 'pilani.bits-pilani.ac.in' },
  { name: 'Birla Institute of Technology and Science Goa', shortName: 'BITS Goa', city: 'Goa', state: 'Goa', emailDomain: 'goa.bits-pilani.ac.in' },
  { name: 'Birla Institute of Technology and Science Hyderabad', shortName: 'BITS Hyderabad', city: 'Hyderabad', state: 'Telangana', emailDomain: 'hyderabad.bits-pilani.ac.in' },
  { name: 'Birla Institute of Technology Mesra', shortName: 'BIT Mesra', city: 'Ranchi', state: 'Jharkhand', emailDomain: 'bitmesra.ac.in' },
  { name: 'Indian Institute of Science Education and Research Pune', shortName: 'IISER Pune', city: 'Pune', state: 'Maharashtra', emailDomain: 'iiserpune.ac.in' },
  { name: 'Indian Institute of Science Education and Research Mohali', shortName: 'IISER Mohali', city: 'Mohali', state: 'Punjab', emailDomain: 'iisermohali.ac.in' },
  { name: 'Indian Institute of Science Education and Research Kolkata', shortName: 'IISER Kolkata', city: 'Kolkata', state: 'West Bengal', emailDomain: 'iiserkol.ac.in' },
  { name: 'Indian Institute of Science Education and Research Bhopal', shortName: 'IISER Bhopal', city: 'Bhopal', state: 'Madhya Pradesh', emailDomain: 'iiserbhopal.ac.in' },
  { name: 'Indian Institute of Science Education and Research Trivandrum', shortName: 'IISER TVM', city: 'Thiruvananthapuram', state: 'Kerala', emailDomain: 'iisertvm.ac.in' },
  { name: 'Indian Institute of Science Education and Research Tirupati', shortName: 'IISER Tirupati', city: 'Tirupati', state: 'Andhra Pradesh', emailDomain: 'iisertirupati.ac.in' },
  { name: 'Indian Institute of Science Education and Research Berhampur', shortName: 'IISER Berhampur', city: 'Berhampur', state: 'Odisha', emailDomain: 'iiserbpr.ac.in' },
  { name: 'Indian Association for the Cultivation of Science', shortName: 'IACS', city: 'Kolkata', state: 'West Bengal', emailDomain: 'iacs.res.in' },

// ── India: top private universities ──
  { name: 'Vellore Institute of Technology Vellore', shortName: 'VIT Vellore', city: 'Vellore', state: 'Tamil Nadu', emailDomain: 'vit.ac.in' },
  { name: 'Vellore Institute of Technology Chennai', shortName: 'VIT Chennai', city: 'Chennai', state: 'Tamil Nadu', emailDomain: 'vit.ac.in' },
  { name: 'Vellore Institute of Technology Andhra Pradesh', shortName: 'VIT-AP', city: 'Amaravati', state: 'Andhra Pradesh', emailDomain: 'vitap.ac.in' },
  { name: 'Vellore Institute of Technology Bhopal', shortName: 'VIT Bhopal', city: 'Bhopal', state: 'Madhya Pradesh', emailDomain: 'vitbhopal.ac.in' },
  { name: 'SRM Institute of Science and Technology', shortName: 'SRM', city: 'Chennai', state: 'Tamil Nadu', emailDomain: 'srmist.edu.in' },
  { name: 'SRM University Delhi NCR Sonepat', shortName: 'SRM Sonepat', city: 'Sonipat', state: 'Haryana', emailDomain: 'srmist.edu.in' },
  { name: 'SRM University Andhra Pradesh', shortName: 'SRM AP', city: 'Amaravati', state: 'Andhra Pradesh', emailDomain: 'srmap.edu.in' },
  { name: 'Manipal Institute of Technology', shortName: 'MIT Manipal', city: 'Manipal', state: 'Karnataka', emailDomain: 'manipal.edu' },
  { name: 'Manipal University Jaipur', shortName: 'MU Jaipur', city: 'Jaipur', state: 'Rajasthan', emailDomain: 'jaipur.manipal.edu' },
  { name: 'Symbiosis Institute of Technology', shortName: 'SIT', city: 'Pune', state: 'Maharashtra', emailDomain: 'sitpune.edu.in' },
  { name: 'Amity University Noida', shortName: 'Amity Noida', city: 'Noida', state: 'Uttar Pradesh', emailDomain: 'amity.edu' },
  { name: 'Amity University Mumbai', shortName: 'Amity Mumbai', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'amity.edu' },
  { name: 'Amity University Kolkata', shortName: 'Amity Kolkata', city: 'Kolkata', state: 'West Bengal', emailDomain: 'amity.edu' },
  { name: 'Bennett University', shortName: 'Bennett', city: 'Greater Noida', state: 'Uttar Pradesh', emailDomain: 'bennett.edu.in' },
  { name: 'Ashoka University', shortName: 'Ashoka', city: 'Sonipat', state: 'Haryana', emailDomain: 'ashoka.edu.in' },
  { name: 'OP Jindal Global University', shortName: 'JGU', city: 'Sonipat', state: 'Haryana', emailDomain: 'jgu.edu.in' },
  { name: 'Shiv Nadar University', shortName: 'SNU', city: 'Greater Noida', state: 'Uttar Pradesh', emailDomain: 'snu.edu.in' },
  { name: 'BML Munjal University', shortName: 'BMU', city: 'Gurugram', state: 'Haryana', emailDomain: 'bmu.edu.in' },
  { name: 'Nirma University', shortName: 'Nirma', city: 'Ahmedabad', state: 'Gujarat', emailDomain: 'nirmauni.ac.in' },
  { name: 'Pandit Deendayal Energy University', shortName: 'PDEU', city: 'Gandhinagar', state: 'Gujarat', emailDomain: 'pdeu.ac.in' },
  { name: 'Kalinga Institute of Industrial Technology', shortName: 'KIIT', city: 'Bhubaneswar', state: 'Odisha', emailDomain: 'kiit.ac.in' },
  { name: 'Siksha O Anusandhan University', shortName: 'SOA', city: 'Bhubaneswar', state: 'Odisha', emailDomain: 'soa.ac.in' },
  { name: 'R.V. College of Engineering', shortName: 'RVCE', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'rvce.edu.in' },
  { name: 'BMS College of Engineering', shortName: 'BMSCE', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'bmsce.ac.in' },
  { name: 'MS Ramaiah Institute of Technology', shortName: 'MSRIT', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'msrit.edu' },
  { name: 'PES University', shortName: 'PES', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'pes.edu' },
  { name: 'BNM Institute of Technology', shortName: 'BNMIT', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'bnmit.org' },
  { name: 'Siddaganga Institute of Technology', shortName: 'SIT Tumkur', city: 'Tumakuru', state: 'Karnataka', emailDomain: 'sit.ac.in' },
  { name: 'NIE Mysuru', shortName: 'NIE', city: 'Mysuru', state: 'Karnataka', emailDomain: 'nie.ac.in' },
  { name: 'College of Engineering Pune', shortName: 'COEP', city: 'Pune', state: 'Maharashtra', emailDomain: 'coep.org.in' },
  { name: 'Vishwakarma Institute of Technology', shortName: 'VIT Pune', city: 'Pune', state: 'Maharashtra', emailDomain: 'vit.edu' },
  { name: 'MIT World Peace University', shortName: 'MIT-WPU', city: 'Pune', state: 'Maharashtra', emailDomain: 'mitwpu.edu.in' },
  { name: 'Dwarkadas J. Sanghvi College of Engineering', shortName: 'DJ Sanghvi', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'djsce.ac.in' },
  { name: 'K J Somaiya College of Engineering', shortName: 'Somaiya', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'somaiya.edu' },
  { name: 'Thadomal Shahani Engineering College', shortName: 'TSEC', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'tsec.edu' },
  { name: 'Sardar Patel Institute of Technology', shortName: 'SPIT', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'spit.ac.in' },
  { name: 'Vidyalankar Institute of Technology', shortName: 'VIT Mumbai', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'vidyalankar.org' },
  { name: 'Inderprastha Engineering College', shortName: 'IPEC', city: 'Ghaziabad', state: 'Uttar Pradesh', emailDomain: 'ipec.org.in' },
  { name: 'JSS Academy of Technical Education Noida', shortName: 'JSS Noida', city: 'Noida', state: 'Uttar Pradesh', emailDomain: 'jssaten.ac.in' },
  { name: 'Galgotias College of Engineering and Technology', shortName: 'GCET', city: 'Greater Noida', state: 'Uttar Pradesh', emailDomain: 'gcet.edu.in' },
  { name: 'Galgotias University', shortName: 'GU', city: 'Greater Noida', state: 'Uttar Pradesh', emailDomain: 'galgotiasuniversity.edu.in' },
  { name: 'Jaypee Institute of Information Technology', shortName: 'JIIT', city: 'Noida', state: 'Uttar Pradesh', emailDomain: 'jiit.ac.in' },
  { name: 'Jaypee University of Engineering and Technology', shortName: 'JUET', city: 'Guna', state: 'Madhya Pradesh', emailDomain: 'juet.ac.in' },
  { name: 'Medi-Caps University', shortName: 'Medicaps', city: 'Indore', state: 'Madhya Pradesh', emailDomain: 'medicaps.ac.in' },
  { name: 'Vivekananda Institute of Professional Studies', shortName: 'VIPS', city: 'New Delhi', state: 'Delhi', emailDomain: 'vips.edu' },
  { name: 'Graphic Era University', shortName: 'GEU', city: 'Dehradun', state: 'Uttarakhand', emailDomain: 'geu.ac.in' },
  { name: 'University of Petroleum and Energy Studies', shortName: 'UPES', city: 'Dehradun', state: 'Uttarakhand', emailDomain: 'upes.ac.in' },
  { name: 'Thapar Institute of Engineering and Technology', shortName: 'Thapar', city: 'Patiala', state: 'Punjab', emailDomain: 'thapar.edu' },
  { name: 'Chandigarh University', shortName: 'CU', city: 'Mohali', state: 'Punjab', emailDomain: 'cumail.in' },
  { name: 'Lovely Professional University', shortName: 'LPU', city: 'Phagwara', state: 'Punjab', emailDomain: 'lpu.in' },
  { name: 'Chitkara University', shortName: 'Chitkara', city: 'Rajpura', state: 'Punjab', emailDomain: 'chitkara.edu.in' },
  { name: 'Amrita Vishwa Vidyapeetham', shortName: 'Amrita', city: 'Coimbatore', state: 'Tamil Nadu', emailDomain: 'amrita.edu' },
  { name: 'SASTRA University', shortName: 'SASTRA', city: 'Thanjavur', state: 'Tamil Nadu', emailDomain: 'sastra.edu' },
  { name: 'SSN College of Engineering', shortName: 'SSN', city: 'Chennai', state: 'Tamil Nadu', emailDomain: 'ssn.edu.in' },
  { name: 'Kumaraguru College of Technology', shortName: 'KCT', city: 'Coimbatore', state: 'Tamil Nadu', emailDomain: 'kct.ac.in' },
  { name: 'PSG College of Technology', shortName: 'PSG', city: 'Coimbatore', state: 'Tamil Nadu', emailDomain: 'psgtech.ac.in' },
  { name: 'National Institute of Design', shortName: 'NID', city: 'Ahmedabad', state: 'Gujarat', emailDomain: 'nid.edu' },
  { name: 'National Institute of Fashion Technology', shortName: 'NIFT', city: 'New Delhi', state: 'Delhi', emailDomain: 'nift.ac.in' },
  { name: 'Symbiosis Centre for Management Studies', shortName: 'SCMS', city: 'Pune', state: 'Maharashtra', emailDomain: 'scms.edu.in' },
  { name: 'Narsee Monjee Institute of Management Studies', shortName: 'NMIMS', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'nmims.edu' },
  { name: 'S.P. Jain Institute of Management and Research', shortName: 'SPJIMR', city: 'Mumbai', state: 'Maharashtra', emailDomain: 'spjimr.org' },
  { name: 'Management Development Institute', shortName: 'MDI', city: 'Gurugram', state: 'Haryana', emailDomain: 'mdi.ac.in' },
  { name: 'XLRI Xavier School of Management', shortName: 'XLRI', city: 'Jamshedpur', state: 'Jharkhand', emailDomain: 'xlri.ac.in' },
  { name: 'Indian Institute of Foreign Trade', shortName: 'IIFT', city: 'New Delhi', state: 'Delhi', emailDomain: 'iift.edu' },
  { name: 'All India Institute of Medical Sciences Delhi', shortName: 'AIIMS Delhi', city: 'New Delhi', state: 'Delhi', emailDomain: 'aiims.edu' },
  { name: 'Christian Medical College Vellore', shortName: 'CMC Vellore', city: 'Vellore', state: 'Tamil Nadu', emailDomain: 'cmcvellore.ac.in' },
  { name: 'Armed Forces Medical College', shortName: 'AFMC', city: 'Pune', state: 'Maharashtra', emailDomain: 'afmc.nic.in' },
  { name: 'Maulana Azad Medical College', shortName: 'MAMC', city: 'New Delhi', state: 'Delhi', emailDomain: 'mamc.ac.in' },
  { name: 'Government Medical College', shortName: 'GMC', city: 'Kozhikode', state: 'Kerala', emailDomain: 'gmckozhikode.ac.in' },
  { name: 'National Law University Delhi', shortName: 'NLUD', city: 'New Delhi', state: 'Delhi', emailDomain: 'nludelhi.ac.in' },
  { name: 'National Academy of Legal Studies and Research', shortName: 'NALSAR', city: 'Hyderabad', state: 'Telangana', emailDomain: 'nalsar.ac.in' },
  { name: 'National Law School of India University', shortName: 'NLSIU', city: 'Bengaluru', state: 'Karnataka', emailDomain: 'nls.ac.in' },
  { name: 'Gujarat National Law University', shortName: 'GNLU', city: 'Gandhinagar', state: 'Gujarat', emailDomain: 'gnlu.ac.in' },
  { name: 'Hidayatullah National Law University', shortName: 'HNLU', city: 'Raipur', state: 'Chhattisgarh', emailDomain: 'hnlu.ac.in' },
  { name: 'Rajiv Gandhi National University of Law', shortName: 'RGNUL', city: 'Patiala', state: 'Punjab', emailDomain: 'rgnul.ac.in' },

  // ── United States ──
  { name: 'Massachusetts Institute of Technology', shortName: 'MIT', city: 'Cambridge', state: 'MA' },
  { name: 'Harvard University', shortName: 'Harvard', city: 'Cambridge', state: 'MA' },
  { name: 'Stanford University', shortName: 'Stanford', city: 'Stanford', state: 'CA' },
  { name: 'University of California Berkeley', shortName: 'UC Berkeley', city: 'Berkeley', state: 'CA' },
  { name: 'California Institute of Technology', shortName: 'Caltech', city: 'Pasadena', state: 'CA' },
  { name: 'Carnegie Mellon University', shortName: 'CMU', city: 'Pittsburgh', state: 'PA' },
  { name: 'Georgia Institute of Technology', shortName: 'Georgia Tech', city: 'Atlanta', state: 'GA' },
  { name: 'University of Illinois Urbana-Champaign', shortName: 'UIUC', city: 'Urbana', state: 'IL' },
  { name: 'University of Michigan Ann Arbor', shortName: 'UMich', city: 'Ann Arbor', state: 'MI' },
  { name: 'University of Texas at Austin', shortName: 'UT Austin', city: 'Austin', state: 'TX' },
  { name: 'Cornell University', shortName: 'Cornell', city: 'Ithaca', state: 'NY' },
  { name: 'Princeton University', shortName: 'Princeton', city: 'Princeton', state: 'NJ' },
  { name: 'Yale University', shortName: 'Yale', city: 'New Haven', state: 'CT' },
  { name: 'Columbia University', shortName: 'Columbia', city: 'New York', state: 'NY' },
  { name: 'University of Pennsylvania', shortName: 'UPenn', city: 'Philadelphia', state: 'PA' },
  { name: 'Duke University', shortName: 'Duke', city: 'Durham', state: 'NC' },
  { name: 'University of Washington', shortName: 'UW', city: 'Seattle', state: 'WA' },
  { name: 'University of California Los Angeles', shortName: 'UCLA', city: 'Los Angeles', state: 'CA' },
  { name: 'New York University', shortName: 'NYU', city: 'New York', state: 'NY' },
  { name: 'University of Southern California', shortName: 'USC', city: 'Los Angeles', state: 'CA' },
  { name: 'Purdue University', shortName: 'Purdue', city: 'West Lafayette', state: 'IN' },
  { name: 'Ohio State University', shortName: 'Ohio State', city: 'Columbus', state: 'OH' },
  { name: 'Pennsylvania State University', shortName: 'Penn State', city: 'State College', state: 'PA' },
  { name: 'University of Florida', shortName: 'UF', city: 'Gainesville', state: 'FL' },
  { name: 'Arizona State University', shortName: 'ASU', city: 'Tempe', state: 'AZ' },
  { name: 'University of Maryland College Park', shortName: 'UMD', city: 'College Park', state: 'MD' },
  { name: 'North Carolina State University', shortName: 'NC State', city: 'Raleigh', state: 'NC' },
  { name: 'Texas A&M University', shortName: 'Texas A&M', city: 'College Station', state: 'TX' },
  { name: 'University of Wisconsin Madison', shortName: 'UW Madison', city: 'Madison', state: 'WI' },
  { name: 'Boston University', shortName: 'BU', city: 'Boston', state: 'MA' },
  { name: 'Northeastern University', shortName: 'Northeastern', city: 'Boston', state: 'MA' },
  { name: 'University of Massachusetts Amherst', shortName: 'UMass', city: 'Amherst', state: 'MA' },
  { name: 'Rutgers University', shortName: 'Rutgers', city: 'New Brunswick', state: 'NJ' },
  { name: 'Indiana University Bloomington', shortName: 'IU', city: 'Bloomington', state: 'IN' },
  { name: 'University of Minnesota Twin Cities', shortName: 'UMN', city: 'Minneapolis', state: 'MN' },
  { name: 'Virginia Polytechnic Institute and State University', shortName: 'Virginia Tech', city: 'Blacksburg', state: 'VA' },
  { name: 'Rensselaer Polytechnic Institute', shortName: 'RPI', city: 'Troy', state: 'NY' },
  { name: 'University of California San Diego', shortName: 'UCSD', city: 'San Diego', state: 'CA' },
  { name: 'University of California Davis', shortName: 'UC Davis', city: 'Davis', state: 'CA' },
  { name: 'University of California Irvine', shortName: 'UCI', city: 'Irvine', state: 'CA' },
  { name: 'Johns Hopkins University', shortName: 'JHU', city: 'Baltimore', state: 'MD' },
  { name: 'Northwestern University', shortName: 'Northwestern', city: 'Evanston', state: 'IL' },
  { name: 'Brown University', shortName: 'Brown', city: 'Providence', state: 'RI' },
  { name: 'Dartmouth College', shortName: 'Dartmouth', city: 'Hanover', state: 'NH' },
  { name: 'Vanderbilt University', shortName: 'Vanderbilt', city: 'Nashville', state: 'TN' },
  { name: 'Rice University', shortName: 'Rice', city: 'Houston', state: 'TX' },
  { name: 'Washington University in St. Louis', shortName: 'WashU', city: 'St. Louis', state: 'MO' },
  { name: 'University of Notre Dame', shortName: 'Notre Dame', city: 'Notre Dame', state: 'IN' },
  { name: 'Georgia State University', shortName: 'GSU', city: 'Atlanta', state: 'GA' },
  { name: 'University of Colorado Boulder', shortName: 'CU Boulder', city: 'Boulder', state: 'CO' },
  { name: 'University of Utah', shortName: 'UU', city: 'Salt Lake City', state: 'UT' },
  { name: 'Oregon State University', shortName: 'OSU', city: 'Corvallis', state: 'OR' },
  { name: 'University of Arizona', shortName: 'UA', city: 'Tucson', state: 'AZ' },
  { name: 'Florida State University', shortName: 'FSU', city: 'Tallahassee', state: 'FL' },
  { name: 'Miami University', shortName: 'Miami U', city: 'Oxford', state: 'OH' },
  { name: 'Syracuse University', shortName: 'Syracuse', city: 'Syracuse', state: 'NY' },
  { name: 'University of South Florida', shortName: 'USF', city: 'Tampa', state: 'FL' },
  { name: 'San Jose State University', shortName: 'SJSU', city: 'San Jose', state: 'CA' },
  { name: 'San Francisco State University', shortName: 'SFSU', city: 'San Francisco', state: 'CA' },
  { name: 'California State University Long Beach', shortName: 'CSULB', city: 'Long Beach', state: 'CA' },
  { name: 'California Polytechnic State University San Luis Obispo', shortName: 'Cal Poly', city: 'San Luis Obispo', state: 'CA' },
  { name: 'University of North Carolina at Chapel Hill', shortName: 'UNC', city: 'Chapel Hill', state: 'NC' },
  { name: 'University of Virginia', shortName: 'UVA', city: 'Charlottesville', state: 'VA' },
  { name: 'Georgia College & State University', shortName: 'Georgia College', city: 'Milledgeville', state: 'GA' },
  { name: 'Texas Tech University', shortName: 'Texas Tech', city: 'Lubbock', state: 'TX' },
  { name: 'Baylor University', shortName: 'Baylor', city: 'Waco', state: 'TX' },
  { name: 'Louisiana State University', shortName: 'LSU', city: 'Baton Rouge', state: 'LA' },
  { name: 'Auburn University', shortName: 'Auburn', city: 'Auburn', state: 'AL' },
  { name: 'University of Alabama', shortName: 'Bama', city: 'Tuscaloosa', state: 'AL' },
  { name: 'Clemson University', shortName: 'Clemson', city: 'Clemson', state: 'SC' },
  { name: 'University of South Carolina', shortName: 'UofSC', city: 'Columbia', state: 'SC' },
  { name: 'University of Tennessee Knoxville', shortName: 'UTK', city: 'Knoxville', state: 'TN' },
  { name: 'University of Kentucky', shortName: 'UK', city: 'Lexington', state: 'KY' },
  { name: 'West Virginia University', shortName: 'WVU', city: 'Morgantown', state: 'WV' },
  { name: 'Kansas State University', shortName: 'K-State', city: 'Manhattan', state: 'KS' },
  { name: 'University of Kansas', shortName: 'KU', city: 'Lawrence', state: 'KS' },
  { name: 'Iowa State University', shortName: 'Iowa State', city: 'Ames', state: 'IA' },
  { name: 'University of Iowa', shortName: 'Iowa', city: 'Iowa City', state: 'IA' },
  { name: 'Mississippi State University', shortName: 'MSU', city: 'Starkville', state: 'MS' },
  { name: 'University of Mississippi', shortName: 'Ole Miss', city: 'Oxford', state: 'MS' },
  { name: 'University of Arkansas', shortName: 'Arkansas', city: 'Fayetteville', state: 'AR' },
  { name: 'Oklahoma State University', shortName: 'OKState', city: 'Stillwater', state: 'OK' },
  { name: 'University of Oklahoma', shortName: 'OU', city: 'Norman', state: 'OK' },
  { name: 'University of Nebraska Lincoln', shortName: 'UNL', city: 'Lincoln', state: 'NE' },
  { name: 'Washington State University', shortName: 'WSU', city: 'Pullman', state: 'WA' },
  { name: 'University of Oregon', shortName: 'UO', city: 'Eugene', state: 'OR' },
  { name: 'Portland State University', shortName: 'PSU', city: 'Portland', state: 'OR' },
  { name: 'University of Nevada Las Vegas', shortName: 'UNLV', city: 'Las Vegas', state: 'NV' },
  { name: 'Boise State University', shortName: 'Boise State', city: 'Boise', state: 'ID' },
  { name: 'Brigham Young University', shortName: 'BYU', city: 'Provo', state: 'UT' },
  { name: 'Temple University', shortName: 'Temple', city: 'Philadelphia', state: 'PA' },
  { name: 'University of Pittsburgh', shortName: 'Pitt', city: 'Pittsburgh', state: 'PA' },
  { name: 'Drexel University', shortName: 'Drexel', city: 'Philadelphia', state: 'PA' },
  { name: 'University at Buffalo', shortName: 'UB', city: 'Buffalo', state: 'NY' },
  { name: 'Stony Brook University', shortName: 'Stony Brook', city: 'Stony Brook', state: 'NY' },
  { name: 'Binghamton University', shortName: 'Binghamton', city: 'Binghamton', state: 'NY' },
  { name: 'George Mason University', shortName: 'GMU', city: 'Fairfax', state: 'VA' },
  { name: 'Virginia Commonwealth University', shortName: 'VCU', city: 'Richmond', state: 'VA' },
  { name: 'University of Connecticut', shortName: 'UConn', city: 'Storrs', state: 'CT' },
  { name: 'University of Delaware', shortName: 'UD', city: 'Newark', state: 'DE' },
  { name: 'University of Vermont', shortName: 'UVM', city: 'Burlington', state: 'VT' },
  { name: 'University of New Hampshire', shortName: 'UNH', city: 'Durham', state: 'NH' },
  { name: 'University of Maine', shortName: 'UMaine', city: 'Orono', state: 'ME' },
  { name: 'DePaul University', shortName: 'DePaul', city: 'Chicago', state: 'IL' },
  { name: 'Illinois Institute of Technology', shortName: 'IIT Chicago', city: 'Chicago', state: 'IL' },
  { name: 'Loyola University Chicago', shortName: 'LUC', city: 'Chicago', state: 'IL' },
  { name: 'Michigan State University', shortName: 'MSU', city: 'East Lansing', state: 'MI' },
  { name: 'Wayne State University', shortName: 'Wayne', city: 'Detroit', state: 'MI' },
  { name: 'Marquette University', shortName: 'Marquette', city: 'Milwaukee', state: 'WI' },
  { name: 'University of Cincinnati', shortName: 'UC', city: 'Cincinnati', state: 'OH' },
  { name: 'Case Western Reserve University', shortName: 'CWRU', city: 'Cleveland', state: 'OH' },
  { name: 'Kent State University', shortName: 'Kent State', city: 'Kent', state: 'OH' },
  { name: 'Miami Dade College', shortName: 'MDC', city: 'Miami', state: 'FL' },
  { name: 'University of Central Florida', shortName: 'UCF', city: 'Orlando', state: 'FL' },
  { name: 'University of Miami', shortName: 'UMiami', city: 'Coral Gables', state: 'FL' },
  { name: 'Florida International University', shortName: 'FIU', city: 'Miami', state: 'FL' },
  { name: 'Emory University', shortName: 'Emory', city: 'Atlanta', state: 'GA' },
  { name: 'Savannah College of Art and Design', shortName: 'SCAD', city: 'Savannah', state: 'GA' },
  { name: 'University of Houston', shortName: 'UH', city: 'Houston', state: 'TX' },
  { name: 'Southern Methodist University', shortName: 'SMU', city: 'Dallas', state: 'TX' },
  { name: 'Barnard College', shortName: 'Barnard', city: 'New York', state: 'NY' },
  { name: 'Fordham University', shortName: 'Fordham', city: 'New York', state: 'NY' },
  { name: 'Cooper Union', shortName: 'Cooper', city: 'New York', state: 'NY' },
  { name: 'New Jersey Institute of Technology', shortName: 'NJIT', city: 'Newark', state: 'NJ' },
  { name: 'Seton Hall University', shortName: 'SHU', city: 'South Orange', state: 'NJ' },
  { name: 'George Washington University', shortName: 'GWU', city: 'Washington', state: 'DC' },
  { name: 'Georgetown University', shortName: 'Georgetown', city: 'Washington', state: 'DC' },
  { name: 'American University', shortName: 'AU', city: 'Washington', state: 'DC' },
  { name: 'Howard University', shortName: 'Howard', city: 'Washington', state: 'DC' },
  { name: 'University of Chicago', shortName: 'UChicago', city: 'Chicago', state: 'IL' },

  // ── United Kingdom ──
  { name: 'University of Oxford', shortName: 'Oxford', city: 'Oxford', state: 'England' },
  { name: 'University of Cambridge', shortName: 'Cambridge', city: 'Cambridge', state: 'England' },
  { name: 'Imperial College London', shortName: 'Imperial', city: 'London', state: 'England' },
  { name: 'London School of Economics and Political Science', shortName: 'LSE', city: 'London', state: 'England' },
  { name: 'University College London', shortName: 'UCL', city: 'London', state: 'England' },
  { name: "King's College London", shortName: "KCL", city: 'London', state: 'England' },
  { name: 'University of Edinburgh', shortName: 'Edinburgh', city: 'Edinburgh', state: 'Scotland' },
  { name: 'University of Manchester', shortName: 'Manchester', city: 'Manchester', state: 'England' },
  { name: 'University of Bristol', shortName: 'Bristol', city: 'Bristol', state: 'England' },
  { name: 'University of Warwick', shortName: 'Warwick', city: 'Coventry', state: 'England' },
  { name: 'University of Glasgow', shortName: 'Glasgow', city: 'Glasgow', state: 'Scotland' },
  { name: 'University of Birmingham', shortName: 'Birmingham', city: 'Birmingham', state: 'England' },
  { name: 'University of Leeds', shortName: 'Leeds', city: 'Leeds', state: 'England' },
  { name: 'University of Sheffield', shortName: 'Sheffield', city: 'Sheffield', state: 'England' },
  { name: 'University of Nottingham', shortName: 'Nottingham', city: 'Nottingham', state: 'England' },
  { name: 'University of Southampton', shortName: 'Southampton', city: 'Southampton', state: 'England' },
  { name: 'Newcastle University', shortName: 'Newcastle', city: 'Newcastle', state: 'England' },
  { name: 'University of Liverpool', shortName: 'Liverpool', city: 'Liverpool', state: 'England' },
  { name: 'Durham University', shortName: 'Durham', city: 'Durham', state: 'England' },
  { name: 'University of Bath', shortName: 'Bath', city: 'Bath', state: 'England' },
  { name: 'University of Exeter', shortName: 'Exeter', city: 'Exeter', state: 'England' },
  { name: 'Lancaster University', shortName: 'Lancaster', city: 'Lancaster', state: 'England' },
  { name: 'University of York', shortName: 'York', city: 'York', state: 'England' },
  { name: 'Cardiff University', shortName: 'Cardiff', city: 'Cardiff', state: 'Wales' },
  { name: 'Queen\'s University Belfast', shortName: 'QUB', city: 'Belfast', state: 'Northern Ireland' },
  { name: 'University of St Andrews', shortName: 'St Andrews', city: 'St Andrews', state: 'Scotland' },
  { name: 'London Business School', shortName: 'LBS', city: 'London', state: 'England' },
  { name: 'Queen Mary University of London', shortName: 'QMUL', city: 'London', state: 'England' },
  { name: 'Royal Holloway University of London', shortName: 'RHUL', city: 'Egham', state: 'England' },
  { name: 'University of Surrey', shortName: 'Surrey', city: 'Guildford', state: 'England' },
  { name: 'Loughborough University', shortName: 'Loughborough', city: 'Loughborough', state: 'England' },

  // ── Canada ──
  { name: 'University of Toronto', shortName: 'UofT', city: 'Toronto', state: 'Ontario' },
  { name: 'University of British Columbia', shortName: 'UBC', city: 'Vancouver', state: 'BC' },
  { name: 'McGill University', shortName: 'McGill', city: 'Montreal', state: 'Quebec' },
  { name: 'University of Waterloo', shortName: 'Waterloo', city: 'Waterloo', state: 'Ontario' },
  { name: 'McMaster University', shortName: 'McMaster', city: 'Hamilton', state: 'Ontario' },
  { name: 'Western University', shortName: 'Western', city: 'London', state: 'Ontario' },
  { name: 'University of Alberta', shortName: 'UAlberta', city: 'Edmonton', state: 'Alberta' },
  { name: 'Queen\'s University', shortName: 'QueensU', city: 'Kingston', state: 'Ontario' },
  { name: 'Simon Fraser University', shortName: 'SFU', city: 'Burnaby', state: 'BC' },
  { name: 'University of Montreal', shortName: 'UdeM', city: 'Montreal', state: 'Quebec' },
  { name: 'University of Calgary', shortName: 'UCalgary', city: 'Calgary', state: 'Alberta' },
  { name: 'University of Ottawa', shortName: 'uOttawa', city: 'Ottawa', state: 'Ontario' },
  { name: 'York University', shortName: 'YorkU', city: 'Toronto', state: 'Ontario' },
  { name: 'Carleton University', shortName: 'Carleton', city: 'Ottawa', state: 'Ontario' },
  { name: 'Dalhousie University', shortName: 'Dal', city: 'Halifax', state: 'Nova Scotia' },
  { name: 'Concordia University', shortName: 'Concordia', city: 'Montreal', state: 'Quebec' },
  { name: 'University of Victoria', shortName: 'UVic', city: 'Victoria', state: 'BC' },
  { name: 'Seneca Polytechnic', shortName: 'Seneca', city: 'Toronto', state: 'Ontario' },
  { name: 'Humber College', shortName: 'Humber', city: 'Toronto', state: 'Ontario' },
  { name: 'George Brown College', shortName: 'GBC', city: 'Toronto', state: 'Ontario' },

  // ── Australia & New Zealand ──
  { name: 'University of Melbourne', shortName: 'UniMelb', city: 'Melbourne', state: 'VIC' },
  { name: 'Australian National University', shortName: 'ANU', city: 'Canberra', state: 'ACT' },
  { name: 'University of Sydney', shortName: 'USYD', city: 'Sydney', state: 'NSW' },
  { name: 'University of New South Wales', shortName: 'UNSW', city: 'Sydney', state: 'NSW' },
  { name: 'Monash University', shortName: 'Monash', city: 'Melbourne', state: 'VIC' },
  { name: 'University of Queensland', shortName: 'UQ', city: 'Brisbane', state: 'QLD' },
  { name: 'University of Western Australia', shortName: 'UWA', city: 'Perth', state: 'WA' },
  { name: 'University of Adelaide', shortName: 'Adelaide', city: 'Adelaide', state: 'SA' },
  { name: 'RMIT University', shortName: 'RMIT', city: 'Melbourne', state: 'VIC' },
  { name: 'University of Technology Sydney', shortName: 'UTS', city: 'Sydney', state: 'NSW' },
  { name: 'Macquarie University', shortName: 'Macquarie', city: 'Sydney', state: 'NSW' },
  { name: 'Queensland University of Technology', shortName: 'QUT', city: 'Brisbane', state: 'QLD' },
  { name: 'Curtin University', shortName: 'Curtin', city: 'Perth', state: 'WA' },
  { name: 'University of Auckland', shortName: 'UoA', city: 'Auckland', state: 'Auckland' },
  { name: 'University of Otago', shortName: 'Otago', city: 'Dunedin', state: 'Otago' },

  // ── Singapore & Hong Kong ──
  { name: 'National University of Singapore', shortName: 'NUS', city: 'Singapore', state: 'Singapore' },
  { name: 'Nanyang Technological University', shortName: 'NTU', city: 'Singapore', state: 'Singapore' },
  { name: 'Singapore Management University', shortName: 'SMU', city: 'Singapore', state: 'Singapore' },
  { name: 'Singapore University of Technology and Design', shortName: 'SUTD', city: 'Singapore', state: 'Singapore' },
  { name: 'University of Hong Kong', shortName: 'HKU', city: 'Hong Kong', state: 'Hong Kong' },
  { name: 'Chinese University of Hong Kong', shortName: 'CUHK', city: 'Hong Kong', state: 'Hong Kong' },
  { name: 'Hong Kong University of Science and Technology', shortName: 'HKUST', city: 'Hong Kong', state: 'Hong Kong' },
  { name: 'City University of Hong Kong', shortName: 'CityU', city: 'Hong Kong', state: 'Hong Kong' },

  // ── Europe ──
  { name: 'Technical University of Munich', shortName: 'TUM', city: 'Munich', state: 'Germany' },
  { name: 'RWTH Aachen University', shortName: 'RWTH', city: 'Aachen', state: 'Germany' },
  { name: 'University of Berlin', shortName: 'HU Berlin', city: 'Berlin', state: 'Germany' },
  { name: 'ETH Zurich', shortName: 'ETH', city: 'Zurich', state: 'Switzerland' },
  { name: 'EPFL', shortName: 'EPFL', city: 'Lausanne', state: 'Switzerland' },
  { name: 'Delft University of Technology', shortName: 'TU Delft', city: 'Delft', state: 'Netherlands' },
  { name: 'Eindhoven University of Technology', shortName: 'TU/e', city: 'Eindhoven', state: 'Netherlands' },
  { name: 'University of Amsterdam', shortName: 'UvA', city: 'Amsterdam', state: 'Netherlands' },
  { name: 'Delft Institute of Technology', shortName: 'TU Delft', city: 'Delft', state: 'Netherlands' },
  { name: 'KU Leuven', shortName: 'KUL', city: 'Leuven', state: 'Belgium' },
  { name: 'Sorbonne University', shortName: 'Sorbonne', city: 'Paris', state: 'France' },
  { name: 'Grandes Écoles Paris', shortName: 'Grandes Écoles', city: 'Paris', state: 'France' },
  { name: 'Politecnico di Milano', shortName: 'PoliMi', city: 'Milan', state: 'Italy' },
  { name: 'Sapienza University of Rome', shortName: 'Sapienza', city: 'Rome', state: 'Italy' },
  { name: 'Technical University of Madrid', shortName: 'UPM', city: 'Madrid', state: 'Spain' },
  { name: 'University of Barcelona', shortName: 'UB', city: 'Barcelona', state: 'Spain' },
  { name: 'KTH Royal Institute of Technology', shortName: 'KTH', city: 'Stockholm', state: 'Sweden' },
  { name: 'Lund University', shortName: 'Lund', city: 'Lund', state: 'Sweden' },
  { name: 'Technical University of Denmark', shortName: 'DTU DK', city: 'Kongens Lyngby', state: 'Denmark' },
  { name: 'Norwegian University of Science and Technology', shortName: 'NTNU', city: 'Trondheim', state: 'Norway' },
  { name: 'Aalto University', shortName: 'Aalto', city: 'Espoo', state: 'Finland' },
  { name: 'University of Vienna', shortName: 'Uni Wien', city: 'Vienna', state: 'Austria' },
  { name: 'Charles University', shortName: 'Charles', city: 'Prague', state: 'Czechia' },
  { name: 'University of Warsaw', shortName: 'UW', city: 'Warsaw', state: 'Poland' },
  { name: 'Middle East Technical University', shortName: 'METU', city: 'Ankara', state: 'Turkey' },
  { name: 'Bogazici University', shortName: 'Bogazici', city: 'Istanbul', state: 'Turkey' },

  // ── UAE, Gulf, Africa & South Asia ──
  { name: 'Khalifa University', shortName: 'KU', city: 'Abu Dhabi', state: 'UAE' },
  { name: 'United Arab Emirates University', shortName: 'UAEU', city: 'Al Ain', state: 'UAE' },
  { name: 'American University of Sharjah', shortName: 'AUS', city: 'Sharjah', state: 'UAE' },
  { name: 'University of Wollongong in Dubai', shortName: 'UOWD', city: 'Dubai', state: 'UAE' },
  { name: 'Manipal Academy of Higher Education Dubai', shortName: 'MAHE Dubai', city: 'Dubai', state: 'UAE' },
  { name: 'King Abdullah University of Science and Technology', shortName: 'KAUST', city: 'Thuwal', state: 'Saudi Arabia' },
  { name: 'King Saud University', shortName: 'KSU', city: 'Riyadh', state: 'Saudi Arabia' },
  { name: 'Qatar University', shortName: 'QU', city: 'Doha', state: 'Qatar' },
  { name: 'American University of Beirut', shortName: 'AUB', city: 'Beirut', state: 'Lebanon' },
  { name: 'Cairo University', shortName: 'Cairo U', city: 'Cairo', state: 'Egypt' },
  { name: 'University of the Witwatersrand', shortName: 'Wits', city: 'Johannesburg', state: 'South Africa' },
  { name: 'University of Cape Town', shortName: 'UCT', city: 'Cape Town', state: 'South Africa' },
  { name: 'University of Nairobi', shortName: 'UoN', city: 'Nairobi', state: 'Kenya' },
  { name: 'University of Lagos', shortName: 'UNILAG', city: 'Lagos', state: 'Nigeria' },
  { name: 'Covenant University', shortName: 'CU', city: 'Ota', state: 'Nigeria' },
  { name: 'Ashesi University', shortName: 'Ashesi', city: 'Accra', state: 'Ghana' },
  { name: 'BRAC University', shortName: 'BRAC', city: 'Dhaka', state: 'Bangladesh' },
  { name: 'Bangladesh University of Engineering and Technology', shortName: 'BUET', city: 'Dhaka', state: 'Bangladesh' },
  { name: 'University of Dhaka', shortName: 'DU Dhaka', city: 'Dhaka', state: 'Bangladesh' },
  { name: 'University of Colombo', shortName: 'UoC', city: 'Colombo', state: 'Sri Lanka' },
  { name: 'Tribhuvan University', shortName: 'TU Nepal', city: 'Kathmandu', state: 'Nepal' },
  { name: 'Kathmandu University', shortName: 'KU Nepal', city: 'Dhulikhel', state: 'Nepal' },

  // ── Latin America & others ──
  { name: 'Universidade de São Paulo', shortName: 'USP', city: 'São Paulo', state: 'Brazil' },
  { name: 'State University of Campinas', shortName: 'Unicamp', city: 'Campinas', state: 'Brazil' },
  { name: 'Universidad Nacional Autónoma de México', shortName: 'UNAM', city: 'Mexico City', state: 'Mexico' },
  { name: 'Tecnológico de Monterrey', shortName: 'Tec', city: 'Monterrey', state: 'Mexico' },
  { name: 'University of Buenos Aires', shortName: 'UBA', city: 'Buenos Aires', state: 'Argentina' },
  { name: 'National University of Singapore Singapore', shortName: 'NUS SG', city: 'Singapore', state: 'Singapore' },
];

/** Normalize a college name so duplicates collapse ("iit delhi." → "indian institute of technology delhi" stays distinct but junk formatting disappears). */
export function normalizeCollegeName(name: string): string {
  return name.trim().replace(/\s+/g, ' ').replace(/[.,]/g, '').toLowerCase();
}
